---
- name: Create a container
  docker_container:
    name: casestudy-spring
    image: "{{ docker_image }}"
    ports:
    - "80:8080"
  when:
    - ansible_connection != "docker"

- debug: msg="http://{{ inventory_hostname }}:80/Casestudy_War is URL for your application."
